version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: innyx
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345678
        ports:
            - "3306:3306"
        networks:
            - laravel-network

networks:
    laravel-network:
